apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ciudadano-ai
resources:
- namespace.yaml
- configmap.yaml
- services.yaml
- platform.yaml
- stateful-platform.yaml
- ingress.yaml
- hpa.yaml
- kong-config.yaml
- database-init.yaml
- network-policy.yaml
