apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-services
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-gateway
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - kong
      - frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
